apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero-deployment
spec:
  selector:
    matchLabels:
      app: monero
  replicas: 1
  template:
    metadata:
      labels:
        app: monero
    spec:
      containers:
      - name: monero
        image: servethehome/monero_cpu_minergate